I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not find return label (u'D:\\GitHub\\Shigoto to Koi/game/script_jp.rpy', 1479822113, 87).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\renpy-6.99.11-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\renpy-6.99.11-sdk\renpy\main.py", line 478, in main
    run(restart)
  File "C:\renpy-6.99.11-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\renpy-6.99.11-sdk\renpy\execution.py", line 734, in run_context
    context.run()
  File "lib/windows-i686/00start.rpyc", line 106, in script
  File "C:\renpy-6.99.11-sdk\renpy\ast.py", line 1367, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\renpy-6.99.11-sdk\renpy\execution.py", line 523, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'D:\\GitHub\\Shigoto to Koi/game/script_jp.rpy', 1479822113, 87).

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Shigoto to Koi 0.0.0
